version: '3.5'

services:

  realworld:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ROCKET_ADDRESS=0.0.0.0
    
    depends_on:
      - db

  db:
    image: postgres:14.3-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=realworld
    ports:
      - "5432:5432"

networks:
  postgres:
    driver: bridge
